### ISSUE TITLE
"I broke that dam" name issue!

### ISSUE THREAD

**Issue by TowelRoyale** [feinwarusoftware/awesomobot#108]
The dam command on the marketplace is named weirdly. It's named **"I broke that dam"** when **"I broke the dam!**" would be more fitting.

**Comment by Dragon1320** [comment]
Idea: Make MongoDB look at ids instead of names for updating commands. I don't know why I didn't do this from the start hehe.

**Comment by Umustalldie2** [comment]
I like the exclamation mark
