### ISSUE TITLE
Card Command Bugs

### ISSUE THREAD

**Issue by iTweeno** [feinwarusoftware/awesomobot#160]
Enforcer Jimmy not loading at high levels
Shaman Token not loading at higher levels
Mintberry Crunch's ability area needs to only have 1 recharge and 1 duration
Card alias needs to be running soon (main current complaint)
When a command ends with a number without a pre-variable, treat null as L
When using mX, the card loads up as LVL X. Still right value, but should give the u value and not start with lvl

**Comment by Dragon1320** [comment]
Make these separate issues, move sppd ones into the sppd repo and close this afterwards.
