### ISSUE TITLE
Discord AO Bot ignores Angel Wendy 

### ISSUE THREAD

**Issue by rbrasga** [feinwarusoftware/awesomobot#175]
**Describe the bug**

The discord command `-card angel wendy` (or any variant of it) returns NOTHING.

Command copied from here: https://sppd.feinwaru.com/WendyMysCard

I literally went through every single card in the SPPD Game to copy your card art and upload to http://sppdreplay.ddns.net:8000/

**To Reproduce**
1. Go to discord server/channel that supports feinwaru AO Discord Bot
2. Type command `-card angel wendy`
3. There is NO response from the bot.

**Expected behavior**
I expect a response that includes stats and card art. All other cards return the appropriate response EXCEPT angel wendy.

**Comment by amDavid01** [comment]
Card was corrupted in our server. Deleted it and downloaded it again, works flawlessly
