### ISSUE TITLE
Bot is not showing deleted images in logs

### ISSUE THREAD

**Issue by KrissYethrowe** [feinwarusoftware/awesomobot#35]

**Comment by MattheousDT** [comment]
Images will cause spam. It saves them as links instead

**Comment by Dragon1320** [comment]
ye they dont actually work rip

**Comment by Dragon1320** [comment]
deleted logs don't currently show up in logs

**Comment by Dragon1320** [comment]
also add message edits and other stuff to logs

**Comment by Dragon1320** [comment]
logs dont exist anymore, will add them soon:tm:
