### ISSUE TITLE
command channel restrictions

### ISSUE THREAD

**Issue by superfloree** [feinwarusoftware/awesomobot#45]
it makes more sense to allow -oof and -hmm unrestricted as theyre reactionary commands to things people might say, while restricting the other commands such as -shitlist, -shitme, -activelist, -activeme, -w, -avatar, and the team joining/leaving commands would make more sense as theres no need for those to be in any other channel.

**Comment by Dragon1320** [comment]
remade command permissions and changed channel restrictions
