### ISSUE TITLE
Notify us about people who join

### ISSUE THREAD

**Issue by TowelRoyale** [feinwarusoftware/awesomobot#57]
They can even be random! Some examples would be:

"______ has joined the server. Lame."

"Welcome ______. Come on down and meet some friends of mine!"

It would help us keep track of how many people join in case of a raid as well.

**Comment by Dragon1320** [comment]
instead of public welcome messages, we'll make them appear in a mod only channel, also telling us whether or not the member has been on our server before

**Comment by Dragon1320** [comment]
handled by towelbot
